// this file was auto-generated by wrapit v1.3.3
#include "Wrapper.h"

#include "jlImGuiTestEngine.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ImGuiCaptureContext> : std::false_type { };
  template<> struct DefaultConstructible<ImGuiCaptureContext> : std::false_type { };
}

// Class generating the wrapper for type ImGuiCaptureContext
// signature to use in the veto file: ImGuiCaptureContext
struct JlImGuiCaptureContext: public Wrapper {

  JlImGuiCaptureContext(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ImGuiCaptureContext (" __HERE__ ")");
    // defined in ./imgui_test_engine/imgui_test_engine/imgui_capture_tool.h:90:18
    jlcxx::TypeWrapper<ImGuiCaptureContext>  t = jlModule.add_type<ImGuiCaptureContext>("ImGuiCaptureContext");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ImGuiCaptureContext>>(new jlcxx::TypeWrapper<ImGuiCaptureContext>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes);
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ImGuiCaptureContext>> type_;
};
std::shared_ptr<Wrapper> newJlImGuiCaptureContext(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlImGuiCaptureContext(module));
}
