// this file was auto-generated by wrapit v1.3.3
#include "Wrapper.h"

#include "jlImGuiTestEngine.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<Str> : std::false_type { };
  template<> struct DefaultConstructible<Str> : std::false_type { };
}

// Class generating the wrapper for type Str
// signature to use in the veto file: Str
struct JlStr: public Wrapper {

  JlStr(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type Str (" __HERE__ ")");
    // defined in ./imgui_test_engine/imgui_test_engine/thirdparty/Str/Str.h:138:15
    jlcxx::TypeWrapper<Str>  t = jlModule.add_type<Str>("Str");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<Str>>(new jlcxx::TypeWrapper<Str>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes);
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<Str>> type_;
};
std::shared_ptr<Wrapper> newJlStr(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlStr(module));
}
